version: 2

project_name: godot-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: godot-cli
    main: .
    binary: godot-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Sqoff/godot-cli/cmd.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

  - id: raw
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  extra_files:
    - glob: "./plugin_release/godot_cli_plugin.zip"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
